extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentReports/ExtentReport.html

basefolder.name=target/ExtentReports/archive/Run
basefolder.datetimepattern=d-MMM-YY_HH-mm-ss

screenshot.dir=target/ExtentReports/screenshots/
screenshot.rel.path=./screenshots/

systeminfo.os=Windows
systeminfo.user=mani
systeminfo.build=APIFramework